version: "3.8"

services:
  check:
    image: ghcr.io/vaggeliskls/disk-usage-notifier:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/:/host"
    env_file:
      - .env
    restart: always
