# My custom values to make the configuration easier to use and not repeat the same values
extras:
  host: &host "my-domain.local"
  hostProtocol: "http"
  keycloakConnectUrl: "http://keycloak/keycloak-auth/realms/master/.well-known/openid-configuration"
  keycloakClientId: "opensearch-dashboards"
  keycloakClientSecret: "vLCEf42cShpAWDy7ciArO6n2iuVGczx51" # This is a placeholder, replace with your actual secret

# Global configuration
global:
  # Global image registry to use for all charts
  imageRegistry: ""
  # Global storage class for persistent volumes
  storageClass: ""
# ------------------------------------------------------------------------
# Ingress Controller Configuration
# ------------------------------------------------------------------------
ingress-controller:
  enabled: true
  fullnameOverride: "nginx-ingress-controller"
  # Service configuration
  service:
    type: LoadBalancer

  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
# ------------------------------------------------------------------------
# Keycloak Configuration
# ------------------------------------------------------------------------
keycloak:
  enabled: true
  fullnameOverride: "keycloak"
  # Authentication
  auth:
    adminUser: admin
    adminPassword: "admin123"

  httpRelativePath: "/keycloak-auth/"

  image:
    registry: docker.io
    repository: bitnami/keycloak
    tag: 26.3.0-debian-12-r0

  # Database configuration (using PostgreSQL)
  postgresql:
    enabled: true
    auth:
      postgresPassword: "postgres123"
      username: "keycloak"
      password: "keycloak123"
      database: "keycloak"
    persistence:
      enabled: true
      size: 8Gi

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http: 80
      https: 443

  # Ingress configuration
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: *host
    hostnameStrict: false
    path: "/keycloak-auth"
    pathType: "Prefix"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    tls: false

  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: false

  adminIngress:
    enabled: false

  # Resources
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

  # Enable metrics
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
# ------------------------------------------------------------------------
# OpenSearch Configuration
# ------------------------------------------------------------------------
opensearch:
  enabled: true
  fullnameOverride: "opensearch"
  clusterDomain: "cluster.local"
  persistence:
    enabled: false
  tls:
    enabled: true
    autoGenerated: true
  # config examples
  # /opt/bitnami/opensearch/config/opensearch.yml
  # /opt/bitnami/opensearch/config/opensearch-security/config.yml
  # https://github.com/cht42/opensearch-keycloak/blob/main/opensearch.yml
  extraVolumes:
    - name: security-config
      configMap:
        name: opensearch-security-config
  extraVolumeMounts:
    - name: security-config
      mountPath: /opt/bitnami/opensearch/config/opensearch-security/config.yml
      subPath: config.yml
  dashboards:
    enabled: true
    password: "adminuser1234"
    extraVolumes:
      - name: dashboard-config
        configMap:
          name: opensearch-security-config
    extraVolumeMounts:
      - name: dashboard-config
        mountPath: /opt/bitnami/opensearch-dashboards/config/opensearch_dashboards.yml
        subPath: opensearch_dashboards.yml
    extraEnvVars:
      - name: OPENSEARCH_URL
        value: "https://opensearch:9200"
    replicaCount: 1
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostname: *host
      path: /
      pathType: Prefix
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      tls: false

  # Cluster configuration
  clusterName: "opensearch-cluster"

  ingest:
    enabled: true
    replicaCount: 1

  # Master nodes
  master:
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    persistence:
      enabled: true
      size: 8Gi

  # Data nodes
  data:
    replicaCount: 1
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    persistence:
      enabled: true
      size: 20Gi

  # Coordinating nodes
  coordinating:
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

  # Security configuration
  security:
    enabled: true
    adminPassword: "opensearch123"
    logstashPassword: "logstash123"
    tls:
      autoGenerated: true
      restEncryption: true
  # Service configuration
  service:
    type: ClusterIP
    ports:
      restAPI: 9200
      performance: 9300
